from enum import Enum


class CARAC(Enum):
    HP_FLAT = 0,
    HP_PER = 1,
    ATK_FLAT = 3,
    ATK_PER = 4,
    DEF_FLAT = 5,
    DEF_PER = 6,
    VIT = 8,
    CRIT_RATE = 9,
    CRIT_DMG = 10,
    RES = 11,
    ACCU = 12


DICT_CARAC = {1: CARAC.HP_FLAT,
              2: CARAC.HP_PER,
              3: CARAC.ATK_FLAT,
              4: CARAC.ATK_PER,
              5: CARAC.DEF_FLAT,
              6: CARAC.DEF_PER,
              8: CARAC.VIT,
              9: CARAC.CRIT_RATE,
              10: CARAC.CRIT_DMG,
              11: CARAC.RES,
              12: CARAC.ACCU}

DICT_CARAC_NAME = {CARAC.HP_FLAT: " HP",
                   CARAC.HP_PER: " % HP",
                   CARAC.ATK_FLAT: " ATK",
                   CARAC.ATK_PER: " % ATK",
                   CARAC.DEF_FLAT: " DEF",
                   CARAC.DEF_PER: " % DEF",
                   CARAC.VIT: " VIT",
                   CARAC.CRIT_RATE: " % Tx. crit",
                   CARAC.CRIT_DMG: " % Dmg crit",
                   CARAC.RES: " % Res",
                   CARAC.ACCU: " % Accuracy"}

DICT_MEULE_ANTIQUE = {CARAC.HP_FLAT: 610,
                      CARAC.HP_PER: 12,
                      CARAC.ATK_FLAT: 34,
                      CARAC.ATK_PER: 12,
                      CARAC.DEF_FLAT: 34,
                      CARAC.DEF_PER: 12,
                      CARAC.VIT: 6,
                      CARAC.CRIT_RATE: None,
                      CARAC.CRIT_DMG: None,
                      CARAC.RES: None,
                      CARAC.ACCU: None}

DICT_MEULE_LEG = {CARAC.HP_FLAT: 550,
                  CARAC.HP_PER: 10,
                  CARAC.ATK_FLAT: 30,
                  CARAC.ATK_PER: 10,
                  CARAC.DEF_FLAT: 30,
                  CARAC.DEF_PER: 10,
                  CARAC.VIT: 5,
                  CARAC.CRIT_RATE: None,
                  CARAC.CRIT_DMG: None,
                  CARAC.RES: None,
                  CARAC.ACCU: None}

PROC_CARAC = {CARAC.HP_FLAT: {1: [15, 60],
                              2: [30, 105],
                              3: [45, 165],
                              4: [60, 225],
                              5: [90, 300],
                              6: [135, 375]},
              CARAC.HP_PER: {1: [1, 2],
                             2: [1, 3],
                             3: [2, 5],
                             4: [3, 6],
                             5: [4, 7],
                             6: [5, 8]},
              CARAC.ATK_FLAT: {1: [1, 4],
                               2: [2, 5],
                               3: [3, 8],
                               4: [4, 10],
                               5: [8, 15],
                               6: [10, 20]},
              CARAC.ATK_PER: {1: [1, 2],
                              2: [1, 3],
                              3: [2, 5],
                              4: [3, 6],
                              5: [4, 7],
                              6: [5, 8]},
              CARAC.DEF_FLAT: {1: [1, 4],
                               2: [2, 5],
                               3: [3, 8],
                               4: [4, 10],
                               5: [8, 15],
                               6: [10, 20]},
              CARAC.DEF_PER: {1: [1, 2],
                              2: [1, 3],
                              3: [2, 5],
                              4: [3, 6],
                              5: [4, 7],
                              6: [5, 8]},
              CARAC.VIT: {1: [1, 1],
                          2: [1, 2],
                          3: [1, 3],
                          4: [2, 4],
                          5: [3, 5],
                          6: [4, 6]},
              CARAC.CRIT_RATE: {1: [1, 2],
                                2: [1, 3],
                                3: [1, 3],
                                4: [2, 4],
                                5: [3, 5],
                                6: [4, 6]},
              CARAC.CRIT_DMG: {1: [1, 2],
                               2: [1, 3],
                               3: [2, 4],
                               4: [2, 5],
                               5: [3, 5],
                               6: [4, 7]},
              CARAC.RES: {1: [1, 2],
                          2: [1, 3],
                          3: [2, 4],
                          4: [2, 5],
                          5: [3, 7],
                          6: [4, 8]},
              CARAC.ACCU: {1: [1, 2],
                           2: [1, 3],
                           3: [2, 4],
                           4: [2, 5],
                           5: [3, 7],
                           6: [4, 8]}}

PROC_CARAC_MAX = {CARAC.HP_FLAT: {1: [15, 60],
                                  2: [30, 105],
                                  3: [45, 165],
                                  4: [90, 285],
                                  5: [120, 360],
                                  6: [165, 435]},
                  CARAC.HP_PER: {1: [1, 2],
                                 2: [1, 3],
                                 3: [2, 5],
                                 4: [4, 8],
                                 5: [5, 9],
                                 6: [6, 10]},
                  CARAC.ATK_FLAT: {1: [1, 4],
                                   2: [2, 5],
                                   3: [3, 8],
                                   4: [6, 14],
                                   5: [10, 19],
                                   6: [12, 24]},
                  CARAC.ATK_PER: {1: [1, 2],
                                  2: [1, 3],
                                  3: [2, 5],
                                  4: [4, 8],
                                  5: [5, 9],
                                  6: [6, 10]},
                  CARAC.DEF_FLAT: {1: [1, 4],
                                   2: [2, 5],
                                   3: [3, 8],
                                   4: [6, 14],
                                   5: [10, 19],
                                   6: [12, 24]},
                  CARAC.DEF_PER: {1: [1, 2],
                                  2: [1, 3],
                                  3: [2, 5],
                                  4: [4, 8],
                                  5: [5, 9],
                                  6: [6, 10]},
                  CARAC.VIT: {1: [1, 1],
                              2: [1, 2],
                              3: [1, 3],
                              4: [3, 5],
                              5: [4, 6],
                              6: [4, 7]},
                  CARAC.CRIT_RATE: {1: [1, 2],
                                    2: [1, 3],
                                    3: [1, 3],
                                    4: [3, 5],
                                    5: [4, 6],
                                    6: [5, 7]},
                  CARAC.CRIT_DMG: {1: [1, 2],
                                   2: [1, 3],
                                   3: [2, 4],
                                   4: [3, 7],
                                   5: [4, 7],
                                   6: [5, 9]},
                  CARAC.RES: {1: [1, 2],
                              2: [1, 3],
                              3: [2, 4],
                              4: [3, 7],
                              5: [4, 9],
                              6: [6, 10]},
                  CARAC.ACCU: {1: [1, 2],
                               2: [1, 3],
                               3: [2, 4],
                               4: [2, 5],
                               5: [4, 9],
                               6: [6, 10]}}


class QualityType(Enum):
    BLANCHE = 1,
    MAGIC = 2,
    RARE = 3,
    HERO = 4,
    LEGEND = 5,
    DIM_BLANCHE = 11,
    DIM_MAGIC = 12,
    DIM_RARE = 13,
    DIM_HERO = 14,
    DIM_LEGEND = 15


DICT_PROC_TYPE = {QualityType.BLANCHE: 0,
                  QualityType.MAGIC: 1,
                  QualityType.RARE: 1,
                  QualityType.HERO: 3,
                  QualityType.LEGEND: 4,
                  QualityType.DIM_BLANCHE: 0,
                  QualityType.DIM_MAGIC: 1,
                  QualityType.DIM_RARE: 2,
                  QualityType.DIM_HERO: 3,
                  QualityType.DIM_LEGEND: 4}

DICT_PROC_TYPE_NAME = {QualityType.BLANCHE: "Blanche",
                       QualityType.MAGIC: "Magic",
                       QualityType.RARE: "Rare",
                       QualityType.HERO: "Héroïque",
                       QualityType.LEGEND: "Legend",
                       QualityType.DIM_BLANCHE: "A Blanche",
                       QualityType.DIM_MAGIC: "A Magic",
                       QualityType.DIM_RARE: "A Rare",
                       QualityType.DIM_HERO: "A Héroïqie",
                       QualityType.DIM_LEGEND: "A Legend"}

DICT_EXTRA = {1: QualityType.BLANCHE,
              2: QualityType.MAGIC,
              3: QualityType.RARE,
              4: QualityType.HERO,
              5: QualityType.LEGEND,
              11: QualityType.DIM_BLANCHE,
              12: QualityType.DIM_MAGIC,
              13: QualityType.DIM_RARE,
              14: QualityType.DIM_HERO,
              15: QualityType.DIM_LEGEND}

DICT_GEMME_CARAC = {CARAC.HP_FLAT: [400, 580],
                    CARAC.HP_PER: [9, 13],
                    CARAC.ATK_FLAT: [28, 40],
                    CARAC.ATK_PER: [9, 13],
                    CARAC.DEF_FLAT: [28, 40],
                    CARAC.DEF_PER: [9, 13],
                    CARAC.VIT: [7, 10],
                    CARAC.CRIT_RATE: [6, 9],
                    CARAC.CRIT_DMG: [7, 10],
                    CARAC.RES: [8, 13],
                    CARAC.ACCU: [8, 13]}


class TypeRune(Enum):
    ENERGIE = 1,
    GARDIEN = 2,
    RAPIDE = 3,
    LAME = 4,
    RAGE = 5,
    FOCUS = 6,
    ENDURANCE = 7,
    FATALE = 8,
    DESESPOIR = 9,
    VAMPIRE = 10,
    VIOLENTE = 11,
    NEMESIS = 12,
    VOLONTE = 13,
    PROTECTION = 14,
    VENGEANCE = 15,
    DESTRCUTION = 16,
    COMBAT = 17,
    DETERMINATION = 18,
    AMELIORATION = 19,
    PRECISION = 20,
    TOLERANCE = 21


DICT_TYPE_RUNES = {1: TypeRune.ENERGIE,
                   2: TypeRune.GARDIEN,
                   3: TypeRune.RAPIDE,
                   4: TypeRune.LAME,
                   5: TypeRune.RAGE,
                   6: TypeRune.FOCUS,
                   7: TypeRune.ENDURANCE,
                   8: TypeRune.FATALE,
                   10: TypeRune.DESESPOIR,
                   11: TypeRune.VAMPIRE,
                   13: TypeRune.VIOLENTE,
                   14: TypeRune.NEMESIS,
                   15: TypeRune.VOLONTE,
                   16: TypeRune.PROTECTION,
                   17: TypeRune.VENGEANCE,
                   18: TypeRune.DESTRCUTION,
                   19: TypeRune.COMBAT,
                   20: TypeRune.DETERMINATION,
                   21: TypeRune.AMELIORATION,
                   22: TypeRune.PRECISION,
                   23: TypeRune.TOLERANCE}

DICT_TYPE_RUNES_NAME = {TypeRune.ENERGIE: "Energy",
                        TypeRune.GARDIEN: "Gardian",
                        TypeRune.RAPIDE: "Swift",
                        TypeRune.LAME: "Lame",
                        TypeRune.RAGE: "Rage",
                        TypeRune.FOCUS: "Focus",
                        TypeRune.ENDURANCE: "Endurance",
                        TypeRune.FATALE: "Fatale",
                        TypeRune.DESESPOIR: "Despair",
                        TypeRune.VAMPIRE: "Vampire",
                        TypeRune.VIOLENTE: "Violent",
                        TypeRune.NEMESIS: "Nemesis",
                        TypeRune.VOLONTE: "Will",
                        TypeRune.PROTECTION: "Proctection",
                        TypeRune.VENGEANCE: "Revenge",
                        TypeRune.DESTRCUTION: "Destruction",
                        TypeRune.COMBAT: "Combat",
                        TypeRune.DETERMINATION: "Determination",
                        TypeRune.AMELIORATION: "Amelio",
                        TypeRune.PRECISION: "Precision",
                        TypeRune.TOLERANCE: "Tolerance"}

DICT_PATH_RUNES = {TypeRune.ENERGIE: {1: "view/assets/type_runes/ENERG_1",
                                      2: "view/assets/type_runes/ENERG_2",
                                      3: "view/assets/type_runes/ENERG_3",
                                      4: "view/assets/type_runes/ENERG_4",
                                      5: "view/assets/type_runes/ENERG_5",
                                      6: "view/assets/type_runes/ENERG_6"},
                   TypeRune.GARDIEN: {1: "view/assets/type_runes/GARD_1",
                                      2: "view/assets/type_runes/GARD_2",
                                      3: "view/assets/type_runes/GARD_3",
                                      4: "view/assets/type_runes/GARD_4",
                                      5: "view/assets/type_runes/GARD_5",
                                      6: "view/assets/type_runes/GARD_6"},
                   TypeRune.RAPIDE: {1: "view/assets/type_runes/RAPIDE_1",
                                     2: "view/assets/type_runes/RAPIDE_2",
                                     3: "view/assets/type_runes/RAPIDE_3",
                                     4: "view/assets/type_runes/RAPIDE_4",
                                     5: "view/assets/type_runes/RAPIDE_5",
                                     6: "view/assets/type_runes/RAPIDE_6"},
                   TypeRune.LAME: {1: "view/assets/type_runes/LAME_1",
                                   2: "view/assets/type_runes/LAME_2",
                                   3: "view/assets/type_runes/LAME_3",
                                   4: "view/assets/type_runes/LAME_4",
                                   5: "view/assets/type_runes/LAME_5",
                                   6: "view/assets/type_runes/LAME_6"},
                   TypeRune.RAGE: {1: "view/assets/type_runes/RAGE_1",
                                   2: "view/assets/type_runes/RAGE_2",
                                   3: "view/assets/type_runes/RAGE_3",
                                   4: "view/assets/type_runes/RAGE_4",
                                   5: "view/assets/type_runes/RAGE_5",
                                   6: "view/assets/type_runes/RAGE_6"},
                   TypeRune.FOCUS: {1: "view/assets/type_runes/FOCUS_1",
                                    2: "view/assets/type_runes/FOCUS_2",
                                    3: "view/assets/type_runes/FOCUS_3",
                                    4: "view/assets/type_runes/FOCUS_4",
                                    5: "view/assets/type_runes/FOCUS_5",
                                    6: "view/assets/type_runes/FOCUS_6"},
                   TypeRune.ENDURANCE: {1: "view/assets/type_runes/ENDU_1",
                                        2: "view/assets/type_runes/ENDU_2",
                                        3: "view/assets/type_runes/ENDU_3",
                                        4: "view/assets/type_runes/ENDU_4",
                                        5: "view/assets/type_runes/ENDU_5",
                                        6: "view/assets/type_runes/ENDU_6"},
                   TypeRune.FATALE: {1: "view/assets/type_runes/FATALE_1",
                                     2: "view/assets/type_runes/FATALE_2",
                                     3: "view/assets/type_runes/FATALE_3",
                                     4: "view/assets/type_runes/FATALE_4",
                                     5: "view/assets/type_runes/FATALE_5",
                                     6: "view/assets/type_runes/FATALE_6"},
                   TypeRune.DESESPOIR: {1: "view/assets/type_runes/DESP_1",
                                        2: "view/assets/type_runes/DESP_2",
                                        3: "view/assets/type_runes/DESP_3",
                                        4: "view/assets/type_runes/DESP_4",
                                        5: "view/assets/type_runes/DESP_5",
                                        6: "view/assets/type_runes/DESP_6"},
                   TypeRune.VAMPIRE: {1: "view/assets/type_runes/VAMP_1",
                                      2: "view/assets/type_runes/VAMP_2",
                                      3: "view/assets/type_runes/VAMP_3",
                                      4: "view/assets/type_runes/VAMP_4",
                                      5: "view/assets/type_runes/VAMP_5",
                                      6: "view/assets/type_runes/VAMP_6"},
                   TypeRune.VIOLENTE: {1: "view/assets/type_runes/VIO_1",
                                       2: "view/assets/type_runes/VIO_2",
                                       3: "view/assets/type_runes/VIO_3",
                                       4: "view/assets/type_runes/VIO_4",
                                       5: "view/assets/type_runes/VIO_5",
                                       6: "view/assets/type_runes/VIO_6"},
                   TypeRune.NEMESIS: {1: "view/assets/type_runes/NEME_1",
                                      2: "view/assets/type_runes/NEME_2",
                                      3: "view/assets/type_runes/NEME_3",
                                      4: "view/assets/type_runes/NEME_4",
                                      5: "view/assets/type_runes/NEME_5",
                                      6: "view/assets/type_runes/NEME_6"},
                   TypeRune.VOLONTE: {1: "view/assets/type_runes/VOLO_1",
                                      2: "view/assets/type_runes/VOLO_2",
                                      3: "view/assets/type_runes/VOLO_3",
                                      4: "view/assets/type_runes/VOLO_4",
                                      5: "view/assets/type_runes/VOLO_5",
                                      6: "view/assets/type_runes/VOLO_6"},
                   TypeRune.PROTECTION: {1: "view/assets/type_runes/PROTEC_1",
                                         2: "view/assets/type_runes/PROTEC_2",
                                         3: "view/assets/type_runes/PROTEC_3",
                                         4: "view/assets/type_runes/PROTEC_4",
                                         5: "view/assets/type_runes/PROTEC_5",
                                         6: "view/assets/type_runes/PROTEC_6"},
                   TypeRune.VENGEANCE: {1: "view/assets/type_runes/REVENGE_1",
                                        2: "view/assets/type_runes/REVENGE_2",
                                        3: "view/assets/type_runes/REVENGE_3",
                                        4: "view/assets/type_runes/REVENGE_4",
                                        5: "view/assets/type_runes/REVENGE_5",
                                        6: "view/assets/type_runes/REVENGE_6"},
                   TypeRune.DESTRCUTION: {1: "view/assets/type_runes/DESTRU_1",
                                          2: "view/assets/type_runes/DESTRU_2",
                                          3: "view/assets/type_runes/DESTRU_3",
                                          4: "view/assets/type_runes/DESTRU_4",
                                          5: "view/assets/type_runes/DESTRU_5",
                                          6: "view/assets/type_runes/DESTRU_6"},
                   TypeRune.COMBAT: {1: "view/assets/type_runes/COMBAT_1",
                                     2: "view/assets/type_runes/COMBAT_2",
                                     3: "view/assets/type_runes/COMBAT_3",
                                     4: "view/assets/type_runes/COMBAT_4",
                                     5: "view/assets/type_runes/COMBAT_5",
                                     6: "view/assets/type_runes/COMBAT_6"},
                   TypeRune.DETERMINATION: {1: "view/assets/type_runes/DETER_1",
                                            2: "view/assets/type_runes/DETER_2",
                                            3: "view/assets/type_runes/DETER_3",
                                            4: "view/assets/type_runes/DETER_4",
                                            5: "view/assets/type_runes/DETER_5",
                                            6: "view/assets/type_runes/DETER_6"},
                   TypeRune.AMELIORATION: {1: "view/assets/type_runes/AMELIO_1",
                                           2: "view/assets/type_runes/AMELIO_2",
                                           3: "view/assets/type_runes/AMELIO_3",
                                           4: "view/assets/type_runes/AMELIO_4",
                                           5: "view/assets/type_runes/AMELIO_5",
                                           6: "view/assets/type_runes/AMELIO_6"},
                   TypeRune.PRECISION: {1: "view/assets/type_runes/PRECI_1",
                                        2: "view/assets/type_runes/PRECI_2",
                                        3: "view/assets/type_runes/PRECI_3",
                                        4: "view/assets/type_runes/PRECI_4",
                                        5: "view/assets/type_runes/PRECI_5",
                                        6: "view/assets/type_runes/PRECI_6"},
                   TypeRune.TOLERANCE: {1: "view/assets/type_runes/TOLE_1",
                                        2: "view/assets/type_runes/TOLE_2",
                                        3: "view/assets/type_runes/TOLE_3",
                                        4: "view/assets/type_runes/TOLE_4",
                                        5: "view/assets/type_runes/TOLE_5",
                                        6: "view/assets/type_runes/TOLE_6"},
                   }
